# Generated by Django 4.0.3 on 2022-06-22 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(choices=[(1, 'FILIŻANKA (100ML)'), (2, 'SZKLANKA (200ML)'), (3, 'DUŻY KUBEK (400ML)'), (4, 'BUTELKA 0,5 L'), (5, 'BUTELKA 1 L')])),
                ('real_value', models.IntegerField(null=True)),
                ('date', models.DateTimeField()),
                ('created_at_date', models.DateTimeField(auto_now_add=True)),
                ('created_at_time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'water',
            },
        ),
    ]
