# Generated by Django 4.0.3 on 2022-06-22 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hydration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='water',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='water',
            name='value',
            field=models.PositiveSmallIntegerField(choices=[(1, 'FILIŻANKA (100ML)'), (2, 'SZKLANKA (200ML)'), (3, 'DUŻY KUBEK (400ML)'), (4, 'BUTELKA 0,5 L'), (5, 'BUTELKA 1 L')], null=True),
        ),
    ]
