# Generated by Django 4.0.3 on 2022-06-22 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bieganie'), (2, 'Jazda na rowerze'), (3, 'Trening siłowy'), (4, 'Piłka nożna'), (5, 'Koszykówka'), (6, 'Badminton'), (7, 'Skakanka'), (8, 'Joga'), (9, 'Tenis'), (10, 'Boks')], default=3, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL),
        ),
    ]
