# Generated by Django 4.0.3 on 2022-06-22 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sleep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='duration_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sleep', to=settings.AUTH_USER_MODEL),
        ),
    ]
